_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 35
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
dataset:
    value:
        num_categories: 3
        seed: 42
        test_ratio: 0.15
        train_ratio: 0.7
        val_ratio: 0.15
model:
    value:
        dropout_rates:
            - 0.5807705634994895
            - 0.48930329413821383
            - 0.5355068200013525
        freeze_backbone: false
        hidden_dims:
            - 192
            - 192
            - 128
        hidden_layers: 3
optuna:
    value:
        final_epochs: 50
        n_trials: 20
        trial_epochs: 10
        use_optuna: false
output:
    value:
        log_every_n_epochs: 1
        use_wandb: true
        wandb_entity: koichi19960406
        wandb_project: cycling-perception
        wandb_tags:
            - 3-category
            - perception-model
            - best-params
paths:
    value:
        data_file: /home/kiito/cycling_safety_svi/data/raw/perceptionratings.csv
        img_path: /srv/shared/bicycle_project_roos/images_scaled
        output_dir: /home/kiito/cycling_safety_svi/cycling_safety_svi/modeling/perception_models/output
training:
    value:
        batch_size: 16
        grad_clip_value: 1.47078459448269
        learning_rate: 0.00015391446222995218
        lr_decay_factor: 0.07420914937766805
        num_epochs: 60
        patience: 7
        scheduler_factor: 0.4566395992413277
        scheduler_patience: 4
        warmup_epochs: 10
        warmup_initial_factor: 0.1
        warmup_type: linear
        weight_decay: 0.026453257276556567
        workers: 2
